apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: guineeapps
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8081 # port of the container
      protocol: TCP
    - name: docker
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: nexus
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: guineeapps
  annotations:
    kubernetes.io/ingress.class: nginx
    # Need to increase memory reception on the proxy in order to push big files
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.org/client-max-body-size: "100m"
spec:
  rules:
  - host: nexus.rougeo.lan
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-service
          servicePort: 80
  - host: docker.rougeo.lan
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-service
          servicePort: 5000