apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: guineeapps
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3
          imagePullPolicy: Always
          #env:
          #  - name: JAVA_OPTS
          #    value: -Djenkins.install.runSetupWizard=false
          # resources:
          #   requests:
          #     memory: "4G"
          #     cpu: "1000m"
          #   limits:
          #     memory: "6G"
          #     cpu: "2000m"
          ports:
            - name: http-port
              containerPort: 8081
            - name: docker-port
              containerPort: 5000
          volumeMounts:
            - name: nexus-pv-volume
              mountPath: /nexus-data
      volumes:
        - name: nexus-pv-volume
          persistentVolumeClaim:
            claimName: nexus-pv-claim