apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv-volume
  namespace: guineeapps
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/boubaca/Desktop/kubernetes/volumes/nexus_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pv-claim
  namespace: guineeapps
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi