apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: guineeapps
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000 # port of the container
      protocol: TCP
  selector:
    app: gitea
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitea-ingress
  namespace: guineeapps
  annotations:
    kubernetes.io/ingress.class: nginx
    # Need to increase memory reception on the proxy in order to push big files
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.org/client-max-body-size: "100m"
spec:
  rules:
  - host: gitea.rougeo.lan
    http:
      paths:
      - path: /
        backend:
          serviceName: gitea-service
          servicePort: 80