apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  #namespace: guineeapps
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/boubaca/Desktop/kubernetes/volumes/jenkins_data"