# In GKE need to get RBAC permissions first with
# kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin [--user=<user-name>|--group=<group-name>]
# https://github.com/jenkinsci/kubernetes-plugin/tree/master/src/main/kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: guineeapps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-guineeapps
  namespace: guineeapps
--- 
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: role-guineeapps
  namespace: guineeapps
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: roleBind-guineeapps
  namespace: guineeapps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-guineeapps
subjects:
- kind: ServiceAccount
  name: jenkins-guineeapps
  namespace: guineeapps

# ---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: ClusterRole
# metadata:
#   name: jenkins
# rules:
# - apiGroups:
#   - apps
#   - extensions
#   resources:
#   - deployments
#   - replicasets
#   verbs:
#   - create
#   - delete
#   - deletecollection
#   - get
#   - list
#   - patch
#   - update
#   - watch

# ---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: ClusterRole
# metadata:
#   name: cicd-apps
# rules:
# - apiGroups:
#   - apps
#   - extensions
#   resources:
#   - deployments
#   - replicasets
#   verbs:
#   - create
#   - delete
#   - deletecollection
#   - get
#   - list
#   - patch
#   - update
#   - watch

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: travis-apps
#   namespace: guineeapps
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cicd-apps
# subjects:
# - kind: User
#   name: system:serviceaccount:serviceids:travis
#   apiGroup: rbac.authorization.k8s.io
# - kind: ServiceAccount
#   name: travis
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: jenkins-apps
#   namespace: guineeapps
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cicd-apps
# subjects:
# - kind: User
#   name: system:serviceaccount:serviceids:jenkins
#   apiGroup: rbac.authorization.k8s.io
# - kind: ServiceAccount
#   name: jenkins