apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: sayhello
spec:
  # inputs:
  params:
  - name: who
    description: who to say hello
    default: kitty
  steps:
  - name: sayhello
    image: alpine
    command:
    - /bin/echo
    args:
    - "Hello ${spec.params.who}"
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  tasks:
  - name: sayhelloworld
    taskRef:
      name: sayhello
    params:
    - name: who
      value: world
# ---
# apiVersion: tekton.dev/v1alpha1
# kind: PipelineRun
# metadata:
#   name: demo-pipeline-run-1
# spec:
#   pipelineRef:
#     name: demo-pipeline
#   serviceAccount: 'default'