apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world-2
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World"
    - name: another
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World"
    - name: pythontest
      image: python  # contains python
      script: |
        #!/usr/bin/env python3
        print("Hello from Python!")