# ############################
# # Volumes PersistentVolume #
# ############################
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nexus-pv-volume
#   namespace: guineeapps
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 15Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/Applications/kubernetes_volume"
# #################################
# # Volumes PersistentVolumeClaim #
# #################################
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nexus-pv-claim
#   namespace: guineeapps
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi

#################################
# Volumes PersistentVolumeClaim #
#################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 157.230.67.35
    path: "/thanos_data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  namespace: guineeapps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
