####
# Namespace
####
---
apiVersion: v1
kind: Namespace
metadata:
  name: guineeapps

####
# Deployment
####
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: guineeapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: nginx
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80

####
# Service
####
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: guineeapps
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80 # port of the container
      protocol: TCP
      nodePort: 30001
  selector:
    app: demo-app

####
# Ingress
####
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-ingress  
  namespace: guineeapps
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: gitea.rougeo.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-app-service
            port:
              number: 80